"""empty message

Revision ID: 6e4ca88499bd
Revises: 5869ffa0a326
Create Date: 2020-04-27 21:27:30.378142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e4ca88499bd'
down_revision = '5869ffa0a326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('contact_id', sa.Integer(), nullable=False))
    op.drop_constraint('interactions_conact_id_fkey', 'interactions', type_='foreignkey')
    op.create_foreign_key(None, 'interactions', 'contacts', ['contact_id'], ['id'])
    op.drop_column('interactions', 'conact_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('conact_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'interactions', type_='foreignkey')
    op.create_foreign_key('interactions_conact_id_fkey', 'interactions', 'contacts', ['conact_id'], ['id'])
    op.drop_column('interactions', 'contact_id')
    # ### end Alembic commands ###
